name: pedal_maps
description: Pedal Maps Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for the application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  geolocator: ^6.1.6
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.0.6
  location: ^3.0.2
  cloud_firestore: ^0.14.3
  firebase_auth: ^0.18.3
  provider: ^4.3.2+2
  flutter_spinkit: ^4.1.2
#
#  cloud_firestore:
#
#  firebase_auth:
#  google_sign_in:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  test: ^1.15.7


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/PedalMapsLogo.png
    - assets/markerIcon.png
